name: med_prep
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  slimy_card:
    git:
      url: https://github.com/imejiasoft/SlimyCard-Animated-Flutter-Package.git
  after_layout: ^1.1.0
  auto_size_text: ^3.0.0
  bubble: ^1.2.1
  video_player: ^2.5.0
  wakelock: ^0.4.0
 
  pretty_dio_logger: ^1.2.0-beta-1
  cached_network_image: ^3.1.0
  cupertino_icons: ^1.0.3
  cupertino_tabbar: ^2.0.0
  delayed_display: ^2.0.0
  dio: ^5.5.0+1

  firebase_core: 
  firebase_messaging: ^15.0.4
  flutter_easyloading: ^3.0.3
  flutter_html: ^3.0.0-beta.2
  flutter_screenutil: ^5.0.0+2
  flutter_secure_storage: ^9.2.2
  flutter_spinkit: ^5.1.0
  flutter_svg: 
  flutter_widget_from_html_core: ^0.15.1
  fluttertoast: ^8.0.8
  font_awesome_flutter: ^10.1.0
  get: ^4.3.8
  get_it: ^7.2.0
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  internet_connection_checker: ^1.0.0+1
  introduction_screen: ^3.0.2
  localstorage: ^5.0.0
  mime: ^1.0.0
  modal_bottom_sheet: ^2.0.0
  percent_indicator: ^4.2.3
  photo_view: ^0.15.0
  provider: ^6.0.0
  pull_to_refresh: ^2.0.0
  shared_preferences: ^2.0.8
  shimmer: ^3.0.0
  simple_timer: ^2.0.0
  socket_io_client: ^2.0.0
  syncfusion_flutter_charts: ^26.2.7
  timeago: ^3.1.0
  timer_count_down: ^2.2.0
  uuid: ^4.4.2
  validators: ^3.0.0
  url_launcher: ^6.0.11
  flutter_cached_pdfview: ^0.4.0-nullsafety
  image_cropper: ^8.0.1
  date_format: ^2.0.4
  carousel_slider: ^4.0.0
  datetime_picker_formfield: ^2.0.0
  firebase_core_platform_interface: ^5.2.0
  # Device Info
  device_info: ^2.0.2
  get_version:
    git:
      url: https://github.com/aryalg/get_version.git
  crypton: ^2.0.3
  version: ^3.0.2
  intl: ^0.19.0
  ntp: ^2.0.0

dependency_overrides:
  modal_bottom_sheet: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/logo.png"

  flutter_lints: ^3.0.0
flutter:
  uses-material-design: true


  assets:
    - assets/icons/categories/
    - assets/icons/tabs/
    - assets/icons/profile/
    - assets/icons/payment/
    - assets/icons/
    - assets/images/
    - assets/images/short_Images/
    - assets/images/clinical_Images/
    - assets/images/country/
    - assets/images/favicon/
    - assets/html/
    - assets/images/background/
    - assets/json/
    - assets/offers/
    - assets/pdf/
    - assets/esewa/
    #- lib/config/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Schyler
      fonts:
      - asset: assets/fonts/Entypo.ttf
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
