// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfXSR_LuJMSgE0_G3SJ5l07BSS1dadwfw',
    appId: '1:467552885441:web:f5712a84211f4fe0705240',
    messagingSenderId: '467552885441',
    projectId: 'medapp-baf92',
    authDomain: 'medapp-baf92.firebaseapp.com',
    storageBucket: 'medapp-baf92.appspot.com',
    measurementId: 'G-20S7LS170C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjkJdaTW2iv0uBGX3cDel-FCTxe_VaaFo',
    appId: '1:467552885441:android:5b38022dfa65e4a1705240',
    messagingSenderId: '467552885441',
    projectId: 'medapp-baf92',
    storageBucket: 'medapp-baf92.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcvc1Z9TL9D39Ssz35YCrpmg5IXPKpV6s',
    appId: '1:467552885441:ios:c69b5ed5b63d7ceb705240',
    messagingSenderId: '467552885441',
    projectId: 'medapp-baf92',
    storageBucket: 'medapp-baf92.appspot.com',
    iosBundleId: 'com.example.medPrep',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcvc1Z9TL9D39Ssz35YCrpmg5IXPKpV6s',
    appId: '1:467552885441:ios:c69b5ed5b63d7ceb705240',
    messagingSenderId: '467552885441',
    projectId: 'medapp-baf92',
    storageBucket: 'medapp-baf92.appspot.com',
    iosBundleId: 'com.example.medPrep',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfXSR_LuJMSgE0_G3SJ5l07BSS1dadwfw',
    appId: '1:467552885441:web:b11d7e944438ed55705240',
    messagingSenderId: '467552885441',
    projectId: 'medapp-baf92',
    authDomain: 'medapp-baf92.firebaseapp.com',
    storageBucket: 'medapp-baf92.appspot.com',
    measurementId: 'G-YZK1NTDN40',
  );
}
